service: bear-store

provider:
  name: aws
  runtime: nodejs8.10
  profile: default
  memorySize: 256
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:eu-central-1:150221128062:table/bears-store"

custom:
  webpackIncludeModules: true

functions:
  hello:
    handler: src/functions/index.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-webpack
  - serverless-offline

