service: bear-store

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  stage: prod
  region: eu-central-1
  environment:
    SECRET: ${env:SECRET, file(./config.json):SECRET}
    EMAIL: ${env:EMAIL, file(./config.json):EMAIL}
    PASSWORD: ${env:PASSWORD, file(./config.json):PASSWORD}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:eu-central-1:150221128062:table/bears-store"

custom:
  webpackIncludeModules: true

functions:
  bears:
    handler: src/functions/index.getBears
    events:
      - http:
         path: bears
         method: get
         cors: true

  express:
    handler:  src/functions/index.handlerExpress
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /login
          method: post
      - http:
          path: /protected
          method: get

plugins:
  - serverless-webpack
  - serverless-offline

